// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH-Pc8XOgM1NJ89AZ7olb-T31PtoIFcVc',
    appId: '1:308467824350:web:f30c2c2d33dea8f311b44f',
    messagingSenderId: '308467824350',
    projectId: 'curriculumcorner-b8191',
    authDomain: 'curriculumcorner-b8191.firebaseapp.com',
    databaseURL: 'https://curriculumcorner-b8191-default-rtdb.firebaseio.com',
    storageBucket: 'curriculumcorner-b8191.appspot.com',
    measurementId: 'G-L26WB5L33Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFlrvMSQZniGx6RmE-s01JD4_mQ7F5iPk',
    appId: '1:308467824350:android:694e55566a39cb3e11b44f',
    messagingSenderId: '308467824350',
    projectId: 'curriculumcorner-b8191',
    databaseURL: 'https://curriculumcorner-b8191-default-rtdb.firebaseio.com',
    storageBucket: 'curriculumcorner-b8191.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzkaAruW2SePFBcs6imelqsu7UCbkjGGk',
    appId: '1:308467824350:ios:b5919998dc086d2711b44f',
    messagingSenderId: '308467824350',
    projectId: 'curriculumcorner-b8191',
    databaseURL: 'https://curriculumcorner-b8191-default-rtdb.firebaseio.com',
    storageBucket: 'curriculumcorner-b8191.appspot.com',
    iosBundleId: 'com.example.curriculumCorner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzkaAruW2SePFBcs6imelqsu7UCbkjGGk',
    appId: '1:308467824350:ios:e0ad966c123fa9ff11b44f',
    messagingSenderId: '308467824350',
    projectId: 'curriculumcorner-b8191',
    databaseURL: 'https://curriculumcorner-b8191-default-rtdb.firebaseio.com',
    storageBucket: 'curriculumcorner-b8191.appspot.com',
    iosBundleId: 'com.example.curriculumCorner.RunnerTests',
  );
}
